name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Install TensorFlow
      run: |
        wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.7.0.tar.gz
        sudo tar -C /usr/local -xzf libtensorflow-cpu-linux-x86_64-2.15.0.tar.gz
        sudo ldconfig
        echo "/usr/local/lib" | sudo tee -a /etc/ld.so.conf.d/libtensorflow.conf
        sudo ldconfig

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
